name: virus_corona_tracker
description: A Flutter App To Track The Stats Of Virus Corona Outbreak

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  draggable_scrollbar: ^0.0.4
  flutter_custom_tabs: ^0.6.0
  flutter_svg: ^0.17.0
  flag: ^1.0.3
  built_collection: ^4.3.2
  built_value: ^7.0.8
  provider: ^4.0.2
  recase: ^3.0.0
  shared_preferences: ^0.5.6+1
  share: ^0.6.3+5
  webview_flutter: ^0.3.19+5
  cupertino_icons: ^0.1.2
  url_launcher:
  intl:
  flare_flutter:
  flutter_icons:
  csv:
  http:
  ant_icons: ^1.0.0
  cached_network_image: ^2.0.0
  launch_review: ^2.0.0
  progress_dialog: ^1.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.3
  built_value_generator: ^7.0.8
  flutter_test:
    sdk: flutter
  percent_indicator: ^2.1.1
  flutter_launcher_icons: ^0.7.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/img_placeholder.png
   - assets/img/laucherhan.webp
   - assets/img/hafeezn.webp
   - assets/img/shian.webp
   - assets/img/tanweiseng.webp
   - assets/img/my.svg
   - lang/en.json
   - lang/vi.json
   - assets/img/bolt.png
   - assets/img/drinkwater.png
   - assets/img/exercise.png
   - assets/img/doctorcheck.png
   - assets/img/face_mask.png
   - assets/img/handwash.png
   - assets/img/down_orange.png
   - assets/img/fish.png
   - assets/img/illustration.png
   - assets/img/sausage.png
   - assets/img/shoe.png
   - assets/img/up_red.png
   - assets/img/icon.png
   - assets/img/icon_about.png
   - assets/flags/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HKGrotesk
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: AbrilFatface
      fonts:
        - asset: assets/fonts/AbrilFatface-Regular.ttf
    - family: Bebas
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf
        - asset: assets/fonts/Lora-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
